/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view.medical.doctor;

import javax.swing.JOptionPane;
import org.bson.Document;
import services.DoctorService;

/**
 *
 * @author priyankakhimyani
 */
public class Diagnosis extends javax.swing.JPanel {

    /**
     * Creates new form Diagnosis
     */
    Document appointment;
    public Diagnosis(Document appointment) {
        initComponents();
        this.appointment = appointment;
        
        nameLabel.setText((String) this.appointment.get("name"));
        fillFields();
        
    }
    
    public void fillFields(){
    
        diagnosisForField.setText((String) this.appointment.get("shownFor"));
        notesField.setText((String) this.appointment.get("notes"));
        medicineField.setText(this.appointment.get("medicine").toString());
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        diagnosisForField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        notesField = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        medicineField = new javax.swing.JTextArea();
        SaveRecord = new javax.swing.JButton();
        historyBtn = new javax.swing.JButton();
        nameLabel = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Diagnosis For");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 101, 141, 35));
        add(diagnosisForField, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 90, 330, 50));

        jLabel2.setText("Notes");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 191, 96, 41));

        notesField.setColumns(20);
        notesField.setRows(5);
        jScrollPane1.setViewportView(notesField);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(226, 169, 332, -1));

        jLabel3.setText("Medicine");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 326, 91, 42));

        medicineField.setColumns(20);
        medicineField.setRows(5);
        jScrollPane2.setViewportView(medicineField);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(226, 301, -1, -1));

        SaveRecord.setText("Save Record");
        SaveRecord.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SaveRecordMouseClicked(evt);
            }
        });
        add(SaveRecord, new org.netbeans.lib.awtextra.AbsoluteConstraints(234, 504, 139, 46));

        historyBtn.setText("View History");
        add(historyBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(428, 504, 168, 46));

        nameLabel.setText("Name");
        add(nameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 210, 30));
    }// </editor-fold>//GEN-END:initComponents

    private void SaveRecordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SaveRecordMouseClicked
        // TODO add your handling code here:
        
        String message = new DoctorService().validateField(diagnosisForField.getText(), notesField.getText(), medicineField.getText());
        
        if(message.length() > 0){
        
            JOptionPane.showMessageDialog(this, message);
        }else{
        
        
            this.appointment.append("shownFor", diagnosisForField.getText());
            this.appointment.append("notes", notesField.getText());
            this.appointment.append("medicine", medicineField.getText());
            
            System.out.println(this.appointment);
            
            int result = new DoctorService().updateAppointment(this.appointment);
            
            if(result >0){
                 JOptionPane.showMessageDialog(this, "Update was successfull");
            }else{
                JOptionPane.showMessageDialog(this, "Error while updating please try again later");
            }
        }
       
        
    }//GEN-LAST:event_SaveRecordMouseClicked
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton SaveRecord;
    private javax.swing.JTextField diagnosisForField;
    private javax.swing.JButton historyBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea medicineField;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JTextArea notesField;
    // End of variables declaration//GEN-END:variables
}
