/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view.medical.doctor;

import Util.EmailSMTP;
import java.io.IOException;
import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.mail.MessagingException;
import javax.swing.JOptionPane;
import model.ActiveUser;
import model.User;
import org.bson.Document;
import org.bson.types.ObjectId;
import services.DoctorService;

/**
 *
 * @author priyankakhimyani
 */
public class Diagnosis extends javax.swing.JPanel {

    /**
     * Creates new form Diagnosis
     */
    Document appointment;
    User user;
    public Diagnosis(Document appointment) {
        initComponents();
        this.appointment = appointment;
        
        nameLabel.setText((String) this.appointment.get("name"));
        fillFields();
        
        this.user = ActiveUser.getActiveUser();
        
    }
    
    public void fillFields(){
    
        diagnosisForField.setText((String) this.appointment.get("shownFor"));
        notesField.setText((String) this.appointment.get("notes"));
        medicineField.setText(this.appointment.get("medicine").toString());
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        diagnosisForField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        notesField = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        medicineField = new javax.swing.JTextArea();
        SaveRecord = new javax.swing.JButton();
        historyBtn = new javax.swing.JButton();
        nameLabel = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(234, 234, 253));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Diagnosis For");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 120, 141, 35));
        add(diagnosisForField, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 110, 420, 50));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("Notes");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 230, 96, 41));

        notesField.setColumns(20);
        notesField.setRows(5);
        jScrollPane1.setViewportView(notesField);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 210, 420, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setText("Medicine");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 360, 91, 42));

        medicineField.setColumns(20);
        medicineField.setRows(5);
        jScrollPane2.setViewportView(medicineField);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 350, 420, 80));

        SaveRecord.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        SaveRecord.setText("Save Record");
        SaveRecord.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SaveRecordMouseClicked(evt);
            }
        });
        add(SaveRecord, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 500, 160, 46));

        historyBtn.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        historyBtn.setText("View History");
        historyBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                historyBtnMouseClicked(evt);
            }
        });
        add(historyBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 500, 168, 46));

        nameLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        nameLabel.setText("Name");
        add(nameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 210, 30));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/Stetho.png"))); // NOI18N
        jLabel4.setText("jLabel4");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(-140, 60, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void SaveRecordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SaveRecordMouseClicked
        // TODO add your handling code here:
        
        String message = new DoctorService().validateField(diagnosisForField.getText(), notesField.getText(), medicineField.getText());
        
        if(message.length() > 0){
        
            JOptionPane.showMessageDialog(this, message);
        }else{
        
        
            this.appointment.append("shownFor", diagnosisForField.getText());
            this.appointment.append("notes", notesField.getText());
            this.appointment.append("medicine", medicineField.getText());
            
            System.out.println(this.appointment);
            
            int result = new DoctorService().updateAppointment(this.appointment);
            
            if(result >0){
                
                try {
                    EmailSMTP email = new EmailSMTP(this.user.getEmail(),
                            (String) this.appointment.get("name"),
                            medicineField.getText(),
                            user.getName());
                    
                    
                    JOptionPane.showMessageDialog(this, "Update was successfull. Email was sent");
                } catch (MessagingException ex) {
                    Logger.getLogger(Diagnosis.class.getName()).log(Level.SEVERE, null, ex);
                } catch (IOException ex) {
                    Logger.getLogger(Diagnosis.class.getName()).log(Level.SEVERE, null, ex);
                }
            }else{
                JOptionPane.showMessageDialog(this, "Error while updating please try again later");
            }
        }
       
        
    }//GEN-LAST:event_SaveRecordMouseClicked

    private void historyBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_historyBtnMouseClicked
        // TODO add your handling code here:
        try {
            PlayerHistory ph = new PlayerHistory((ObjectId)this.appointment.get("medicalId"), this.appointment.get("name").toString());
            ph.setDefaultCloseOperation(1);
        } catch (ParseException ex) {
            Logger.getLogger(Diagnosis.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
    }//GEN-LAST:event_historyBtnMouseClicked
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton SaveRecord;
    private javax.swing.JTextField diagnosisForField;
    private javax.swing.JButton historyBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea medicineField;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JTextArea notesField;
    // End of variables declaration//GEN-END:variables
}
