/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.aed_finalproject;

import Model.Venue;

/**
 *
 * @author Shardul
 */
public class secPanel extends javax.swing.JPanel {

    /**
     * Creates new form secPanel
     */
    Venue venue;
    public secPanel(Venue venue) {
        initComponents();
        this.venue = venue;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        secHedingLabel = new javax.swing.JLabel();
        secUserIDLabel = new javax.swing.JLabel();
        secPasswordLabel = new javax.swing.JLabel();
        secNameLabel = new javax.swing.JLabel();
        secPhoneLabel = new javax.swing.JLabel();
        secEmailLabel = new javax.swing.JLabel();
        secUserIdTextF = new javax.swing.JTextField();
        secNameTextF = new javax.swing.JTextField();
        secPasswordTextF = new javax.swing.JTextField();
        secPhoneTextF = new javax.swing.JTextField();
        secEmailTextF = new javax.swing.JTextField();
        secSearchTextF = new javax.swing.JTextField();
        secSearchButton = new javax.swing.JButton();
        secCreateButton = new javax.swing.JButton();
        secUpdateButton = new javax.swing.JButton();
        secViewButton = new javax.swing.JButton();
        secScrollPane = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        secDeleteButton = new javax.swing.JButton();

        secHedingLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        secHedingLabel.setText("Security");
        secHedingLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        secUserIDLabel.setText("User ID");

        secPasswordLabel.setText("Password");

        secNameLabel.setText("Name");

        secPhoneLabel.setText("Phone");

        secEmailLabel.setText("Email");

        secUserIdTextF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                secUserIdTextFActionPerformed(evt);
            }
        });

        secPasswordTextF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                secPasswordTextFActionPerformed(evt);
            }
        });

        secSearchTextF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                secSearchTextFActionPerformed(evt);
            }
        });

        secSearchButton.setText("Search");

        secCreateButton.setText("Create");
        secCreateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                secCreateButtonActionPerformed(evt);
            }
        });

        secUpdateButton.setText("Update");

        secViewButton.setText("View");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "User ID", "Name", "Phone", "Email"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Long.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        secScrollPane.setViewportView(jTable1);

        secDeleteButton.setText("Delete");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(89, 89, 89)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(secCreateButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(secViewButton)
                        .addGap(18, 18, 18)
                        .addComponent(secUpdateButton)
                        .addGap(18, 18, 18)
                        .addComponent(secDeleteButton)
                        .addGap(226, 226, 226))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(secHedingLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(secEmailLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(secEmailTextF))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(secPhoneLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(secPhoneTextF))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(secPasswordLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(secPasswordTextF, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(secUserIDLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(secNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(secNameTextF, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(secUserIdTextF, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(secScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(secSearchTextF, javax.swing.GroupLayout.PREFERRED_SIZE, 426, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(27, 27, 27)
                            .addComponent(secSearchButton, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(89, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(secHedingLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(secSearchTextF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(secSearchButton))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(secUserIDLabel)
                            .addComponent(secUserIdTextF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(secNameTextF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(secNameLabel))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(secPasswordLabel)
                            .addComponent(secPasswordTextF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(secPhoneLabel)
                            .addComponent(secPhoneTextF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(secEmailLabel)
                            .addComponent(secEmailTextF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(secScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(secCreateButton)
                    .addComponent(secViewButton)
                    .addComponent(secDeleteButton)
                    .addComponent(secUpdateButton))
                .addContainerGap(69, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void secUserIdTextFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_secUserIdTextFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_secUserIdTextFActionPerformed

    private void secPasswordTextFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_secPasswordTextFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_secPasswordTextFActionPerformed

    private void secSearchTextFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_secSearchTextFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_secSearchTextFActionPerformed

    private void secCreateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_secCreateButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_secCreateButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable jTable1;
    private javax.swing.JButton secCreateButton;
    private javax.swing.JButton secDeleteButton;
    private javax.swing.JLabel secEmailLabel;
    private javax.swing.JTextField secEmailTextF;
    private javax.swing.JLabel secHedingLabel;
    private javax.swing.JLabel secNameLabel;
    private javax.swing.JTextField secNameTextF;
    private javax.swing.JLabel secPasswordLabel;
    private javax.swing.JTextField secPasswordTextF;
    private javax.swing.JLabel secPhoneLabel;
    private javax.swing.JTextField secPhoneTextF;
    private javax.swing.JScrollPane secScrollPane;
    private javax.swing.JButton secSearchButton;
    private javax.swing.JTextField secSearchTextF;
    private javax.swing.JButton secUpdateButton;
    private javax.swing.JLabel secUserIDLabel;
    private javax.swing.JTextField secUserIdTextF;
    private javax.swing.JButton secViewButton;
    // End of variables declaration//GEN-END:variables
}
