/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view.systemadmin;

import enums.ROLES;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JSplitPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import services.UserService;
import model.User;
import view.players.panel.UpdateProfilePanel;
/**
 *
 * @author Shardul
 */
public class ViewUserPanel extends javax.swing.JPanel {
    
    private UserService userService;
    private final String ADD_BUTTON_CLICKED="ADD_BUTTON_CLICKED";
    private List<User> userList=new ArrayList<User>();
    private JSplitPane panel;
    private User user;
    /**
     * Creates new form ViewUserPanel
     */
    public ViewUserPanel(JSplitPane panel) {
        
        this.userService=new UserService();
        this.panel=panel;
        initComponents();
        populateTable();
    }
    
    
    private void populateTable(){
        this.userList= this.userService.fetchAllRecords();
        DefaultTableModel dtm=(DefaultTableModel) this.userTable.getModel();
        Object[] row= new Object[dtm.getColumnCount()];
        dtm.setRowCount(0);
        int count=1;
        for(User user:userList){
            row[0]=count;
            count++;
            row[1]=user.getName();
            row[2]=user.getRoles().toString();
            row[3]=user.getEmail();
            row[4]=user.getHeight();
            row[5]=user.getWeight();
            row[6]=user.getUsername();
            row[7]=user.getPhoneNumber();
            dtm.addRow(row);
       }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        userTable = new javax.swing.JTable();
        addBtn = new javax.swing.JButton();
        updateBtn = new javax.swing.JButton();

        userTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "SrNo", "Name", "Role", "email", "height", "weight", "username", "phone"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        userTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                userTableMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                userTableMouseEntered(evt);
            }
        });
        jScrollPane1.setViewportView(userTable);

        addBtn.setText("Add User");
        addBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBtnActionPerformed(evt);
            }
        });

        updateBtn.setText("Update User");
        updateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 796, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(109, 109, 109)
                .addComponent(addBtn)
                .addGap(18, 18, 18)
                .addComponent(updateBtn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addBtn)
                    .addComponent(updateBtn))
                .addGap(0, 153, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void addBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBtnActionPerformed
        // TODO add your handling code here:
        firePropertyChange(ADD_BUTTON_CLICKED, "clicked", "clicked");
    }//GEN-LAST:event_addBtnActionPerformed

    private void updateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateBtnActionPerformed
        // TODO add your handling code here:
        UpdateProfilePanel p = new UpdateProfilePanel(user);
        panel.setRightComponent(p);
        
        
        firePropertyChange(ADD_BUTTON_CLICKED, "clicked", "clicked");
    }//GEN-LAST:event_updateBtnActionPerformed

    private void userTableMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userTableMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_userTableMouseEntered

    private void userTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userTableMouseClicked
        // TODO add your handling code here:
       JTable source = (JTable)evt.getSource();
        int row = source.rowAtPoint( evt.getPoint() );
        
        String userName= userTable.getValueAt(row, 6).toString();
        user=userList.stream().filter((e)->userName.equalsIgnoreCase(e.getUsername())).findFirst().orElse(null);
        //set new Panel call updateProfilePanel(user)
    }//GEN-LAST:event_userTableMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addBtn;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton updateBtn;
    private javax.swing.JTable userTable;
    // End of variables declaration//GEN-END:variables
}
