/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view.players;

import java.awt.Component;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JSplitPane;
import javax.swing.table.DefaultTableModel;
import model.Matches;
import services.MatchesService;
import view.players.TeamView;
import view.players.panel.UpdateProfilePanel;

/**
 *
 * @author Shardul
 */
public class CoachesHomePage extends javax.swing.JFrame {
    public final String ADD_BUTTON_CLICKED="ADD_BUTTON_CLICKED";
    public List<Matches> matchesList = new ArrayList<Matches>();
    public JSplitPane panel;
    public Matches matches;
    int count = 1;
    
    /**
     * Creates new form CoachesHomePage
     */
    private Component rightPanel = new UpdateProfilePanel(null);
    public CoachesHomePage() {
        
        initComponents();
        Games games = new Games();
        splitPane.setRightComponent(games);
        
    }
    

        
    public void populateTable(){
        
        MatchesService matchservice = new MatchesService();
        this.matchesList = matchservice.fetchAllRecords();
        DefaultTableModel dtm=(DefaultTableModel) this.gamesTable.getModel();
        String[] columnNames = { "Count", "Team", "Opponent", "Winner", "Final Score", "Stadium", "MVP" };
        DefaultTableModel model = new DefaultTableModel(columnNames, 0){
                @Override
                public boolean isCellEditable(int row, int column) {
                   //all cells false
                   return false;
                };
        };
        
        matchesList.forEach(match ->{
            
            model.addRow(new Object[] { count, match.getTeam(), match.getOpponent(), match.getWinner(), match.getFinalScore(), match.getStadium(), match.getMvp()});
            count++;
        });
        
        gamesTable.setModel(model);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        splitPane = new javax.swing.JSplitPane();
        leftBackgroundPanel = new javax.swing.JPanel();
        gamesBtn = new javax.swing.JButton();
        teamBtn = new javax.swing.JButton();
        rightBackgroundPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        gamesTable = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        gamesBtn.setText("Games");
        gamesBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gamesBtnActionPerformed(evt);
            }
        });

        teamBtn.setText("Team");
        teamBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                teamBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout leftBackgroundPanelLayout = new javax.swing.GroupLayout(leftBackgroundPanel);
        leftBackgroundPanel.setLayout(leftBackgroundPanelLayout);
        leftBackgroundPanelLayout.setHorizontalGroup(
            leftBackgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(leftBackgroundPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(leftBackgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(gamesBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(leftBackgroundPanelLayout.createSequentialGroup()
                        .addComponent(teamBtn)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        leftBackgroundPanelLayout.setVerticalGroup(
            leftBackgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(leftBackgroundPanelLayout.createSequentialGroup()
                .addGap(105, 105, 105)
                .addComponent(gamesBtn)
                .addGap(58, 58, 58)
                .addComponent(teamBtn)
                .addContainerGap(292, Short.MAX_VALUE))
        );

        splitPane.setLeftComponent(leftBackgroundPanel);

        gamesTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Count", "Team", "Opponent", "Winner", "Final Score", "Mvp"
            }
        ));
        jScrollPane1.setViewportView(gamesTable);

        javax.swing.GroupLayout rightBackgroundPanelLayout = new javax.swing.GroupLayout(rightBackgroundPanel);
        rightBackgroundPanel.setLayout(rightBackgroundPanelLayout);
        rightBackgroundPanelLayout.setHorizontalGroup(
            rightBackgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 635, Short.MAX_VALUE)
        );
        rightBackgroundPanelLayout.setVerticalGroup(
            rightBackgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, rightBackgroundPanelLayout.createSequentialGroup()
                .addGap(0, 74, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        splitPane.setRightComponent(rightBackgroundPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(splitPane)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(splitPane)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void gamesBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gamesBtnActionPerformed
        // TODO add your handling code here:
        Games games = new Games();
        this.splitPane.setRightComponent(games);
    }//GEN-LAST:event_gamesBtnActionPerformed

    private void teamBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_teamBtnActionPerformed
        // TODO add your handling code here:
        this.rightPanel = new TeamView(splitPane);
        this.splitPane.setRightComponent(rightPanel);
    }//GEN-LAST:event_teamBtnActionPerformed

    /**
     * @param args the command line arguments
     */
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton gamesBtn;
    private javax.swing.JTable gamesTable;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel leftBackgroundPanel;
    private javax.swing.JPanel rightBackgroundPanel;
    private javax.swing.JSplitPane splitPane;
    private javax.swing.JButton teamBtn;
    // End of variables declaration//GEN-END:variables
}
