/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view.players;

import java.util.ArrayList;
import java.util.List;
import javax.swing.JSplitPane;
import javax.swing.table.DefaultTableModel;
import location.Location;
import model.Matches;
import services.MatchesService;

/**
 *
 * @author priyankakhimyani
 */
public class Games extends javax.swing.JPanel {

    /**
     * Creates new form Games
     */

    public List<Matches> matchesList = new ArrayList<Matches>();
    int count = 1;
    public Games() {
        initComponents();
        
        MatchesService matchservice = new MatchesService();
        this.matchesList = matchservice.fetchAllRecords();
        DefaultTableModel dtm=(DefaultTableModel) this.gamesTable.getModel();
        String[] columnNames = { "Count", "Team", "Opponent", "Winner", "Final Score", "Stadium", "MVP" };
        DefaultTableModel model = new DefaultTableModel(columnNames, 0){
                @Override
                public boolean isCellEditable(int row, int column) {
                   //all cells false
                   return false;
                };
        };
        
        matchesList.forEach(match ->{
            
            model.addRow(new Object[] { count, match.getTeam(), match.getOpponent(), match.getWinner(), match.getFinalScore(), match.getStadium(), match.getMvp()});
            count++;
        });
        
        gamesTable.setModel(model);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        gamesTable = new javax.swing.JTable();
        gardenArena = new javax.swing.JButton();
        matthewsArena = new javax.swing.JButton();

        gamesTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(gamesTable);

        gardenArena.setText("View TD Garden");
        gardenArena.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                gardenArenaMouseClicked(evt);
            }
        });
        gardenArena.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gardenArenaActionPerformed(evt);
            }
        });

        matthewsArena.setText("View Matthews Arena");
        matthewsArena.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                matthewsArenaMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 679, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(gardenArena, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(matthewsArena, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(86, 86, 86))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(gardenArena, javax.swing.GroupLayout.DEFAULT_SIZE, 49, Short.MAX_VALUE)
                    .addComponent(matthewsArena, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 444, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void gardenArenaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gardenArenaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_gardenArenaActionPerformed

    private void gardenArenaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_gardenArenaMouseClicked
        // TODO add your handling code here:
        Location location = new Location("TD Garden");
        location.setDefaultCloseOperation(1);
        
    }//GEN-LAST:event_gardenArenaMouseClicked

    private void matthewsArenaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_matthewsArenaMouseClicked
        // TODO add your handling code here:
        
        Location location = new Location("Matthews Arena");
        location.setDefaultCloseOperation(1);
    }//GEN-LAST:event_matthewsArenaMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable gamesTable;
    private javax.swing.JButton gardenArena;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton matthewsArena;
    // End of variables declaration//GEN-END:variables
}
