/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package inventory;

/**
 *
 * @author priyankakhimyani
 */
public class IceHockey extends javax.swing.JPanel {

    /**
     * Creates new form IceHockey
     */
    public IceHockey() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        //BufferedImage myPicture = ImageIO.read(new File("ictures/basketball.jpeg"));
        stick = new javax.swing.JLabel(new javax.swing.ImageIcon(getClass().getResource("/Pictures/stick.jpeg")));
        //BufferedImage myPicture = ImageIO.read(new File("ictures/basketball.jpeg"));
        mouthGuard = new javax.swing.JLabel(new javax.swing.ImageIcon(getClass().getResource("/Pictures/mouthGuard.jpeg")));
        //BufferedImage myPicture = ImageIO.read(new File("ictures/basketball.jpeg"));
        pads = new javax.swing.JLabel(new javax.swing.ImageIcon(getClass().getResource("/Pictures/pads.jpeg")));
        //BufferedImage myPicture = ImageIO.read(new File("ictures/basketball.jpeg"));
        gloves = new javax.swing.JLabel(new javax.swing.ImageIcon(getClass().getResource("/Pictures/gloves.jpeg")));
        //BufferedImage myPicture = ImageIO.read(new File("ictures/basketball.jpeg"));
        skates = new javax.swing.JLabel(new javax.swing.ImageIcon(getClass().getResource("/Pictures/skates.jpeg")));
        //BufferedImage myPicture = ImageIO.read(new File("ictures/basketball.jpeg"));
        helmet = new javax.swing.JLabel(new javax.swing.ImageIcon(getClass().getResource("/Pictures/helmet.jpeg")));

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        stick.setText("v");
        stick.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                stickMouseClicked(evt);
            }
        });
        add(stick, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 590, 176, 168));

        mouthGuard.setText("v");
        mouthGuard.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mouthGuardMouseClicked(evt);
            }
        });
        add(mouthGuard, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 590, 176, 168));

        pads.setText("b");
        pads.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                padsMouseClicked(evt);
            }
        });
        add(pads, new org.netbeans.lib.awtextra.AbsoluteConstraints(117, 341, 176, 168));

        gloves.setText("a");
        gloves.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                glovesMouseClicked(evt);
            }
        });
        add(gloves, new org.netbeans.lib.awtextra.AbsoluteConstraints(442, 55, 176, 168));

        skates.setText("a");
        skates.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                skatesMouseClicked(evt);
            }
        });
        add(skates, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 330, 176, 168));

        skates.setSize(80, 80);
        helmet.setBackground(new java.awt.Color(255, 102, 102));
        helmet.setText("a");
        helmet.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                helmetMouseClicked(evt);
            }
        });
        add(helmet, new org.netbeans.lib.awtextra.AbsoluteConstraints(115, 55, 176, 168));
    }// </editor-fold>//GEN-END:initComponents

    private void stickMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_stickMouseClicked
        // TODO add your handling code here:
        Stick stick = new Stick();
        stick.setDefaultCloseOperation(1);
    }//GEN-LAST:event_stickMouseClicked

    private void mouthGuardMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mouthGuardMouseClicked
        // TODO add your handling code here:
        Guard guard = new Guard();
        guard.setDefaultCloseOperation(1);
    }//GEN-LAST:event_mouthGuardMouseClicked

    private void padsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_padsMouseClicked
        // TODO add your handling code here:
        Pads pads = new Pads();
        pads.setDefaultCloseOperation(1);
    }//GEN-LAST:event_padsMouseClicked

    private void glovesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_glovesMouseClicked
        // TODO add your handling code here:
        RingsAndRims rr = new RingsAndRims();
        rr.setDefaultCloseOperation(1);
    }//GEN-LAST:event_glovesMouseClicked

    private void skatesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_skatesMouseClicked
        // TODO add your handling code here:
        Skates skates = new Skates();
        skates.setDefaultCloseOperation(1);

    }//GEN-LAST:event_skatesMouseClicked

    private void helmetMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_helmetMouseClicked
        // TODO add your handling code here:
        Helmet helmet = new Helmet();
        helmet.setDefaultCloseOperation(1);
    }//GEN-LAST:event_helmetMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel gloves;
    private javax.swing.JLabel helmet;
    private javax.swing.JLabel mouthGuard;
    private javax.swing.JLabel pads;
    private javax.swing.JLabel skates;
    private javax.swing.JLabel stick;
    // End of variables declaration//GEN-END:variables
}
