/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.common;

import model.ActiveUser;
import services.UserService;
import model.User;
import enums.ROLES;
import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import view.inventory.Inventory;
import view.players.HomePageFrame;
import view.medical.doctor.DoctorHome;
import view.medical.pharmacy.PharmacyHome;
import view.players.CoachesHomePage;
import view.players.TeamManagerFrame;
import view.systemadmin.SysadminHome;
import view.venue.venueHomePage;

/**
 *
 * @author Shardul
 */
public class LoginFrame extends javax.swing.JFrame {
    
    private UserService userService;
    
    /**
     * Creates new form LoginFrame
     */
    public LoginFrame() {
        initComponents();
        setResizable(false);
        this.userService= new UserService();
        errorMessageLabel.setVisible(false);
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jpanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        userNameTextField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        loginBtn = new javax.swing.JButton();
        passwordField = new javax.swing.JPasswordField();
        errorMessageLabel = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jpanel.setBackground(new java.awt.Color(255, 255, 255));
        jpanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("SPORTS MANAGEMENT SYSTEM");
        jpanel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 130, 400, 38));

        userNameTextField.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        userNameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userNameTextFieldActionPerformed(evt);
            }
        });
        jpanel.add(userNameTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 260, 283, 40));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Username");
        jpanel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 230, 110, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("Password");
        jpanel.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 330, 100, -1));

        loginBtn.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        loginBtn.setText("Login");
        loginBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginBtnActionPerformed(evt);
            }
        });
        jpanel.add(loginBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 440, 106, 35));
        jpanel.add(passwordField, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 360, 281, 33));

        errorMessageLabel.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        errorMessageLabel.setForeground(new java.awt.Color(255, 255, 255));
        errorMessageLabel.setText("Invalid username or password!!!");
        jpanel.add(errorMessageLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 500, 370, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/Person.png"))); // NOI18N
        jLabel6.setText("jLabel6");
        jpanel.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 260, 40, 40));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/Key.png"))); // NOI18N
        jLabel4.setText("jLabel4");
        jpanel.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 350, 40, 50));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/Sprint.png"))); // NOI18N
        jLabel7.setText("jLabel7");
        jpanel.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 70, 50, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/Skates.png"))); // NOI18N
        jLabel8.setText("jLabel7");
        jpanel.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 70, 50, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/Basketball.png"))); // NOI18N
        jLabel9.setText("jLabel7");
        jpanel.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 70, 50, -1));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/Tennis.png"))); // NOI18N
        jLabel10.setText("jLabel7");
        jpanel.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 70, 50, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/BBWallpaper2.jpg"))); // NOI18N
        jLabel5.setText("jLabel5");
        jpanel.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(-590, -200, -1, -1));

        jPanel1.add(jpanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(-4, 1, 1110, 650));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loginBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginBtnActionPerformed
        // TODO add your handling code here:

        String userName= userNameTextField.getText();
        String password= passwordField.getText();

        if(userName==null || password==null || userName.length()<1 || password.length()<1){
            errorMessageLabel.setVisible(true);
            return;
        }
        errorMessageLabel.setVisible(false);
        //call the db function
        if(userService.loginUser(userName, password)){
            try {
                //enable the next screen
                redirectScreen();
            } catch (ParseException ex) {
                Logger.getLogger(LoginFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
            //close the login screen
            
//            JFrame frame=new HomePageFrame();
//            frame.setVisible(true);
        }else{
            errorMessageLabel.setVisible(true);
        }
    }//GEN-LAST:event_loginBtnActionPerformed

    private void userNameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userNameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userNameTextFieldActionPerformed

    
    public void redirectScreen() throws ParseException{
        
        User user= ActiveUser.getActiveUser();
        
        switch(user.getRoles()){
            
            case COACH: 
                CoachesHomePage coach = new CoachesHomePage();
                coach.setVisible(true);
                coach.setDefaultCloseOperation(1);
                break;
            case BBPLAYER:
            case IHPLAYER: 
                HomePageFrame home  = new HomePageFrame();
                home.setVisible(true);
                home.setDefaultCloseOperation(1);
                break;
                           
            case DOCTOR : 
                DoctorHome doctor =  new DoctorHome(user.getId());
                doctor.setVisible(true);
                doctor.setDefaultCloseOperation(1);
                break;
            case VENUEADMIN : venueHomePage ven = new venueHomePage();
                                ven.setVisible(true);
                                ven.setDefaultCloseOperation(1);
                           break;
            case SYSADMIN : SysadminHome sys= new SysadminHome();
                            sys.setVisible(true);
                            sys.setDefaultCloseOperation(1);
                            break;
            case PHARMACY: PharmacyHome pharHome = new PharmacyHome();
                            pharHome.setDefaultCloseOperation(1);
                            break;
            case TEAMMANAGER: TeamManagerFrame tm = new TeamManagerFrame();
                            tm.setDefaultCloseOperation(1);
                            break;
            case IVTADMIN : Inventory iv = new Inventory();
                            iv.setDefaultCloseOperation(1);
                        
            default:
                break;
            //case PLAYER: 
        }
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel errorMessageLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jpanel;
    private javax.swing.JButton loginBtn;
    private javax.swing.JPasswordField passwordField;
    private javax.swing.JTextField userNameTextField;
    // End of variables declaration//GEN-END:variables
}
